:toc:

== Data Source Support
In this section defines all the data sources that Operator Supports and how to configure them and any dependencies it may require.

Please note _any_ property that you want to configure, you can define reference to the value from a `secret` than providing a value directly. For example, the `Password` properties need to be secured, those can defined from secret as below.
----
- name: SPRING_DATASOURCE_SAMPLEDB_PASSWORD
  valueFrom:
     secretKeyRef:
       name: postgresql
       key: password
----

NOTE: When defining a environment property, characters like `.` are not allowed, but you can replace them with character `_` and application will convert them automatically at runtime.

NOTE: If any configured property in a ConfigMap or Secret is missing, the Operator will not start the build until such configuration value is supplied. Also if the configuration changes after the service is running, the service will be automatically redeployed with new values.

NOTE: All the data sources below in addition to what is defined here support "importer.xxxxx" properties are defined on their translator page for further customization. Pleas refer to that documentation on available properties and their possible values and descriptions.

== Configuring Relational Database [[config-jdbc]]
For configuring the translator name in VDB, the follwing translators are supported

- _amazon-athena_
- _actian-vector_
- _db2_
- _derby_
- _exasol_
- _h2_
- _hana_ (SAP Hana using the JDBC driver)
- _hbase_ (HBase using the Phoenix driver)
- _hive_ (Hive using the Hive JDBC driver)
- _hsql_
- _impala_ (Cloudera Impala)
- _informix_
- _ingres_
- _jdbc-simple_
- _jdbc-ansi_
- _jtds_sqlserver_ (Connect Microsoft SQLServer using JTDS drivers)
- _ms-sqlserver_ (Microsoft SQLServer using the Microsoft driver)
- _mysql_
- _netezza_
- _oracle_
- _osisoft-pi_ (OSISOFT's PI Database using osisoft's JDBC Driver)
- _phoenix_ (Apache Phoenix using the Phoenix JDBC Driver)
- _postgresql_
- _prestodb_ (PrestoDB connecting using JDBC Driver)
- _redshift_ (Amazon Red Shift)
- _sap-iq_ 
- _sqlserver_ (Same as ms-sqlserver)
- _sybase_
- _teradata_
- _teiid_ (Connecting to another Teiid instance using its JDBC driver)
- _vertica_

For configuring the relational database like Oracle, MS-SQLServer, PostgreSQL etc, the following properties are required.

[Attributes]
|===
|Property Name |Description |Required|Default value

|jdbc-url | URL For the connection | Yes| n/a
|username| User Name| Yes | n/a
|Pasword | Yes | n/a | n/a
|driver-class-name| Driver Name | No | n/a
|importer.schemaName| Schema Name for import| Yes |n/a
|===

A sample configuration showing the properties for a sample `postgresql` database

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: postgresql
    properties:
      - name: username
        value: postgres
      - name: password
        value: postgres
      - name: jdbc-url
        value: jdbc:postgresql://database/postgres
----

or 

[source, yaml]
.A sample configuration using secrets
----
datasources:
  - name: sampledb
    type: postgresql
    properties:
      - name: username
        valueFrom:
          secretKeyRef:
            name: sampledb-secret
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: sampledb-secret
            key: password
      - name: jdbc-url
        value: jdbc:postgresql://database/postgres
----

NOTE: where {NAME} denotes the custom name given by the user, that defines the `server` in the VDB's DDL. For example, `CREATE SERVER sampledb FOREIGN DATA WRAPPER postgresql` in your DDL where names match EXACTLY to above.

You define many more properties to further tune the JDBC translator and schema import behavior. Please check Teiid translator documentation.

The user is also required to provide a maven dependency for JDBC driver class for the above data source in `spec/dependencies` line in the CR. It is expected that the maven repository is *reachable* by the Operator. If in case the resource is not available in the public/private maven repository then there are other options to solve the issue. Look at section "Attach Private Libraries".


== [[config-mongo]]Configuring MongoDB database
The translator name to use in the VDB's DDL is _mongodb_ with its `Server` definition.

For configuring the MongoDB database the following properties are needed

[Attributes]
|===
|Property Name |Description |Required|Default value
|remoteServerList | List of MongoDb servers ex:(localhost:27012) | Yes | n/a
|user| User Name | Yes | n/a
|password | Password | Yes | n/a
|database | Database name to connect to | Yes | n/a
|authDatabase | Database name for authorization | No | n/a
|ssl | Use SSL Connection | No | n/a
|===

User does not need to add any dependencies. The currently supported version is version 3 of the MongoDB.

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: mongodb
    properties:
      - name: user
        value: user
      - name: password
        value: pass
      - name: remoteServerList
        value: localhost:27012
      - name: database
        value: test
----

== [config-soap]] Configuring SOAP web service data source
The translator name to use in the VDB's DDL is _soap_ or _ws_ with its `Server` definition.

For configuring the SOAP webservice the following properties are needed

[Attributes]
|===
|Property Name |applies to |Required |Default Value |Description

|EndPoint
|HTTP & SOAP
|false
|n/a
|URL for HTTP, Service Endpoint for SOAP.  Not required if using HTTP invoke procedures that specify absolute URLs. Will be used as the base URL if an invoke procedure uses a relative URL.

|SecurityType
|HTTP & SOAP
|false
|none
|Type of Authentication to used with the web service. Allowed values ["None","HTTPBasic"]

|AuthUserName
|HTTP & SOAP
|false
|n/a
|Name value for authentication, used in HTTPBasic and WsSecurity

|AuthPassword
|HTTP & SOAP
|false
|n/a
|Password value for authentication, used in HTTPBasic and WsSecurity

|ConfigFile
|HTTP & SOAP
|false
|n/a
|CXF client configuration File or URL

|EndPointName
|HTTP & SOAP
|false
|teiid
|Local part of the end point QName to use with this connection, needs to match one defined in cxf file

|ServiceName
|SOAP
|false
|n/a
|Local part of the service QName to use with this connection

|NamespaceUri
|SOAP
|false
|http://teiid.org
|Namespace URI of the service QName to use with this connection

|RequestTimeout
|HTTP & SOAP
|false
|n/a
|Timeout for request

|ConnectTimeout
|HTTP & SOAP
|false
|n/a
|Timeout for connection

|Wsdl
|SOAP
|false
|n/a
|WSDL file or URL for the web service
|===

User does not need to add any dependencies.

[source, yaml]
.A sample configuration
----
  datasources:
    - name: soapCountry
      type: soap
      properties:
        - name: wsdl
          value: http://www.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL
        - name: namespaceUri
          value: http://www.oorsprong.org/websamples.countryinfo
        - name: serviceName
          value: CountryInfoService
        - name: endPointName
          value: CountryInfoServiceSoap12
----


== [[config-s3]]Configuring Amazon S3 as Source
The translator name to use in the VDB's DDL is _amazon-s3_ with its `Server` definition.

For configuring the Amazon S3 the following properties are needed

[Attributes]
|===
|Property Name |Description |Required|Default value
|region | S3 region ex: us-east-2 | Yes | n/a
|bucket | Bucket Name | Yes | n/a
|accesskey| Access Key | Yes | n/a
|secretkey| Secret key | Yes | n/a
|===

When Amazon-S3 is setup, one will need to create a bucket and will also can find out the the access-key and secret-key for access from AWS website before configuration for the VDB. User does not need to add any dependencies for this.

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: amazon-s3
    properties:
      - name: region
        value: us-east-2
      - name: bucket
        value: mybucket
      - name: accesskey
        value: xxxxxxxx
      - name: secretkey
        value: xxxxxx
----



== [[config-ispn]] Configuring Infinispan as source
The translator name to use in the VDB's DDL is _infinispan-hotrod_ with its `Server` definition.

For configuring the Infinispan the following properties are needed

[Attributes]
|===
|Property Name |Description |Required|Default value
|url | URL to connect to Infinispan | Yes | n/a
|username | User Name| Yes | n/a
|password | Password | Yes | n/a
|cacheName| default cache name | No | n/a
|authenticationRealm| Auth Realm | No | n/a
|authenticationServerName | Auth Server | No | n/a

|===

User does not need to add any dependencies, as the required client libraries are already provided.

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: infinispan-hotrod
    properties:
      - name: url
        value: localhost:11222
      - name: user
        value: user
      - name: password
        value: pass
      - name: cacheName
        value: test
----


== Configuring Salesforce [[config-sf]]
The translator name to use in the VDB's DDL is _salesforce_ with its `Server` definition.

For connecting to Salesforce and importing/querying all `SObject`, the user fist needs to create `OAuth` based connection in the Salesforce. Log into your Salesforce account, go to
`SetUp -> Create -> Apps`. Then, create a new "Connected App" and provide details there. When you are done, should get a `client-id` and `client-secret` values. Then to use this application from Teiid to connect to Salesforce by configuring the below properties.

[Attributes]
|===
|Property Name |Description |Required|Default value
|url| URL of the salesforce|No|https://login.salesforce.com/services/Soap/u/45.0
|username | User for salesforce.com | Yes | n/a
|password | Password for salesforce.com| Yes | n/a
|clientId | ClientId from connected app | Yes | n/a
|clientSecret | clientSecret from connected app | No | n/a
|refreshToken | Refresh Token | No |n/a
|===

NOTE: if user does not want to connect using the `username` and `password`, then the module also supports using the `refreshToken`. So for above you can provide `refreshToken` property and remove username and password properties. Documenting obtaining of the `refresh token` from is beyond scope of this document.

No further dependencies from user is required for this.The below showing simple user name and password based login.

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: salesforce
    properties:
      - name: userName
        value: user
      - name: password
        value: pass
----

`clientId` and `clientSecret` can be obtained from Salesforce when you create your Salesforce application.

== Configuring OData Based Source [[config-odata]]
The translator name to use in the VDB's DDL is _odata_ with its `Server` definition for any OData V2 services. For OData V4 service use _odata4_

As per the connection underneath, follow the same properties as <<config-rest, REST based connection>>

The below configuration showing `openid_connect` security type with a OData service
[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: odata4
    properties:
      - name: endpoint
        value: https://dv-customer-myproject.apps-crc.testing/odata/accounts/customer
      - name: securityType
        value: openid-connect
      - name: clientId
        value: dv
      - name: clientSecret
        value: xxxxxxxxxxx
      - name: authorizeUrl
        value: https://keycloak-myproject.apps-crc.testing/auth/realms/master/protocol/openid-connect/auth
      - name: accessTokenUrl
        value: https://keycloak-myproject.apps-crc.testing/auth/realms/master/protocol/openid-connect/token        
----

== Configuring SAP Gateway Based Source [[config-sap]]
The translator name to use in the VDB's DDL is _sap-gateway_ with its `Server` definition. This uses OData V2 translator underneath to connect to SAP Gateway. Only _Http Basic_ auth has been verified.

As per the connection underneath, follow the same properties as <<config-rest, REST based connection>>

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: sap-gateway
    properties:
      - name: userName
        value: user
      - name: password
        value: pass
----

== Configuring FTP Based Source [[config-ftp]]
The translator name to use in the VDB's DDL is _ftp_ with its `Server` definition. 

NOTE: The secure FTPS is supported, however to support this user needs to provide trust certificates to system. See the section how to use certificates in the OpenShift/Kubernetes with Virtual Database xref:certificates.adoc[here] 

The following properties can be configured for creating the FTP based source.

[Attributes]
|===
|Property Name |Description |Required|Default value
|host| Host name of the FTP server |yes| n/a
|port| Port of the FTP server |No| 21
|username | User name for remote server login | Yes | n/a
|password | Password  for remote server login | Yes | n/a
|parentDirectory | Directory where file located in remote server | Yes | n/a
|isFtps | Ftp Security | No | false
|===

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampleftp
    type: ftp
    properties:
      - name: host
        value: localhost
      - name: parent-directory
        value: /path/to/file/
      - name: username
        value: user
      - name: password
        value: pass
----

== Configuring OpenAPI Based Source [[config-openapi]]
The translator name to use in the VDB's DDL is _openapi_ with its `Server` definition. When this translator is used, the source will look for endpoint `/openapi` files and build the source model based on it. However if the API document endpoint is defined as something else, one could configure that in the VDB's DDL on schema statement as

----
CREATE SCHEMA sourceModel SERVER oService OPTIONS ("importer.metadataUrl" '/swagger.json');
----

alternatively, one can define a ENVIRONMENT property instead for the same

[source, yaml]
.A sample configuration
----
datasources:
  - name: sampledb
    type: openapi
    properties:
      - name: userName
        value: user
      - name: password
        value: pass
      - name: importer.metadataUrl
        value: /swagger.json
----


If the API is secured, security aspects of the service are not understood automatically, only the API document and its responses are understood by the translator. Those should be defined using REST properties below

As per the connection underneath, follow the same properties as <<config-rest, REST based connection>>

== Configuring REST Based Source [[config-rest]]
For rest based that are using the rest directly can use _rest_ as the translator name. Note, for sources like OData and SAP there are separate translators based on same configuration here. When used directly the user is provided with `invokeHttp` as defined in the Teiid documents to use to execute any endpoint using SQL.

The REST API based connection uses the following properties

[Attributes]
|===
|Property Name |Description |Required|Default value
| endpoint | Endpoint for the service | Yes | n/a
|securityType | Security type used. Available options are _http-basic_, _openid-connect_ or empty | No | no security
|===

if the _security type_ is defined as _http_basic_ the following properties are needed
[Attributes]
|===
|Property Name |Description |Required|Default value
|userName | User Name | Yes | n/a
|password | Password | Yes | n/a
|===

if the _security type_ is defined as _openid-connect_ the following properties are needed
[Attributes]
|===
|Property Name |Description |Required|Default value
|userName | User Name | Yes | n/a
|password | Password | Yes | n/a
|clientId | ClientId from connected app | Yes | n/a
|clientSecret | clientSecret from connected app | Yes | n/a
|authorizeUrl | clientSecret from connected app | Yes | n/a
|accessTokenUrl | clientSecret from connected app | Yes | n/a
|scope | clientSecret from connected app | No | n/a
|===

Alternatively, for the _openid-connect_ you can also supply 'refreshToken' property and avoid the `userName` and `password` properties, however describing on how to obtaining a refresh token is beyond this document as it is different for different services.

NOTE: when using a endpoint that is Http(S) then you might have to configure the truststore for the third party endpoint. To do that, one would need to configure a custom truststore as defined xref:certificates.adoc[here]

== Configuring Google Sheets as Source [[config-googlesheets]]
The translator name to use in the VDB's DDL is _google-spreadsheet_ with its `Server` definition. This will represent each _Sheet_ on a google spread sheet as a _table_ in Teiid.

Before you can access the Google Spreadsheet using Teiid, one needs to provide OAuth2 specific credentials to Teiid. To provide the access, use instructions from https://developers.google.com/identity/protocols/OAuth2InstalledApp and create project ad select the "Google Spreadsheets API" as library you want to access. Then create a "OAuth Client ID" Credential using the UI. At the end of this exercise, you will have a "Client ID" and "Client Secret". Then using the Google's OAuth2.0 Playground https://developers.google.com/oauthplayground/ select the "Google Sheet API v4" option and select "drive" and "spreadsheets" endpoints as allowable scopes. Then Authorize APIs, you will end up with a "RefreshToken". Then use all these properties for further configuration.

[Attributes]
|===
|Property Name |Description |Required|Default value
|spreadSheetName |Name of the Google Spreadsheet | Yes | n/a
|spreadSheetId |Spread Sheet Id | Yes | Sheet Id, Look in URL of the Spreadsheet. For more info see https://developers.google.com/sheets/api/guides/concepts#spreadsheet_id
|clientId |OAuth2 client id for google sheets | Yes | n/a
|clientSecret |OAuth2 client secret for google sheets | Yes | n/a
|refreshToken |OAuth2 refreshToken for google sheets | Yes | n/a
|===
