:toc:

= Data Virtualization on OpenShift

This guide provides documentation and code recipes for deploying and configuring the Data Virtualization on OpenShift. Typically a deployment of Data Virtualization includes defining a Virtual Database (VDB) using SQL/DDL and then configuring any of the data sources this VDB uses to connect and read and write data. Additionally, there may be scenarios where one maybe also configuring the Authentication to RH-SSO.

There are couple different ways one can develop & deploy Data Virtualization.

- Define a YAML file vdb contents, then using the OpenShift Teiid Operator to deploy. Example below.
- Defining a maven based Java project with a VDB file, using Teiid Spring Boot, then using the Teiid Operator to deploy the generated Fat Jar.

The user is expected that they have knowledge of of Openshift and  Operator model and how it works. If you have not already installed the teiid operator in your OpenShift instance, please install using directions xref:install-operator.adoc[here]

NOTE: Each option shown, is the *same* example with different ways of development.

== Virtual Database defined in DDL [[YML_DDL]]

[source,yaml]
.dv-customer.yaml
----
apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: dv-customer
spec:
  replicas: 1 <1>
  env: <2>
  - name: SPRING_DATASOURCE_SAMPLEDB_USERNAME
    value: user
  - name: SPRING_DATASOURCE_SAMPLEDB_PASSWORD
    value: mypassword
  - name: SPRING_DATASOURCE_SAMPLEDB_JDBCURL
    value: jdbc:postgresql://postgresql/$(SPRING_DATASOURCE_SAMPLEDB_DATABASENAME)
  build:
    source:
      dependencies: <3>
        - org.postgresql:postgresql:42.1.4
      ddl: | <4>
        CREATE DATABASE customer OPTIONS (ANNOTATION 'Customer VDB');
        USE DATABASE customer;
        ...
      mavenRepositories: <5>
        central: https://repo.maven.apache.org/maven2
----

<1> define number of instances that you want to deploy. By default this is set to 1

<2> defines the list of all the configuration properties for this virtualization. Mainly connection configuration to the data sources. In above example, it is showing properties to connect to a `PostgreSQL` database. See section on "Data Source Support" for different data sources supported and their required properties to configure.

<3> defines a list of maven dependency JAR files in GAV format (groupId:artifactid:version) especially for defining the JDBC driver files or any custom dependencies for data source. Check specific data source support under "Data Source Support" section. Typically most libraries that are available in public maven repositories are automatically added to the Operator build.

<4> defines VDB in DDL form. Consult the Teiid documentation on for how to build a VDB using DDL. Defining all DDL is beyond scope of this document. 

<5> If in case any dependencies or VDB are defined in a private or non public repositories then use this property to define that repository location. One can configure more than one repository.

A full example is provided here link:https://github.com/teiid/teiid-operator/blob/master/deploy/crs/vdb_from_ddl.yaml[dv-customer.yaml]

== Virtual Database defined as Maven Artifact [[YML_MAVEN]]
This example shows how to deploy a VDB that is defined as maven artifact using the Teiid Operator.

After your VDB is available in a maven repository, you can use a YAML based custom resource similar to below to deploy the VDB in OpenShift.

NOTE: The below YAML file very similar to example above, most portions are are omitted for space and clarity. Looks for full example below.

[source, yaml]
.dv-customer.yaml
----
apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: dv-customer
spec:
   ...
  build:
    source: 
      maven: com.example:customer-vdb:1.0.0:vdb <1>
    mavenRepositories: <2>
      central: https://repo.maven.apache.org/maven2
----

<1> Define maven coordinates to locate the VDB in GAV format. An example VDB that is defined as Maven Artifact is defined here link:https://github.com/teiid/dv-customer[dv-customer]. If you are sharing your VDB, or colloborating and would like to keep the versioned history then one should select to develop the VDB in this fashion. When using VDB-Import feature VDB must be defined in this fashion

<2> If your maven repository is at private location, then provide the link here.

A full example is provided here link:https://github.com/teiid/teiid-operator/blob/master/deploy/crs/vdb_from_maven.yaml[dv-customer.yaml]

== Virtual Database defined as FAT JAR [[YML_DDL]]
This example shows how to deploy a VDB that is defined as FAT JAR that is built using `teiid-springboot` starter.

An example project is defined link:https://github.com/teiid/dv-customer-fatjar[here] shows you how you can use java based project to develop a Virtual Database as a FAT JAR.

After your FAT JAR is available in a maven repository, you can use a YAML based custom resource similar to below to deploy the VDB in OpenShift.

NOTE: The below YAML file is exactly same as the VDB in maven example above, but the <maven> GAV is different. see blow partial fragment with the differences.

[source, yaml]
.dv-customer.yaml
----
 build:
   source:
     maven  org.teiid:dv-customer-fatjar:1.1
----

A full example is provided here link:https://github.com/teiid/teiid-operator/blob/master/deploy/crs/vdb_from_fatjar.yaml[dv-customer.yaml]

== VirtualDatabase Deployment [[deployment-cr]]

Once the Operator is available on your OpenShift cluster you deploy a VDB by executing below and supplying YAML file created

[source,bash]
----
oc create -f dv-customer.yml
----

where `dv-customer.yml` is the CR (custom resource) file that defines your virtualization artifact. 

IMPORTANT:  Before you need to deploy above virtualization, we need to prepare and gather all the configuration that needed for connecting to the data sources involved. For example checkout the "Configuring Relational Database" section below.

One can delete the above virtualization by executing

[source,bash]
----
oc delete vdb dv-customer
----

=== Created Service and Routes
When the virtualization completed with its deployment, it will create a Service with name of the custom resource (`dv-customer` from above example), 

- Port `31000` is available for JDBC connection. 
- Port `35432` will be open for any `PG` specific client including a ODBC client
- A `http` endpoint with route will be available for a `odata`. In above CR, if there is a property `spec/exposeVia3scale` set to `true` then this route will not be created, and it is expected that user will use _3scale_ to manage the endpoint.

== Accessing the deployed Virtualization [vdb-access]
Once virtualization is deployed in the OpenShift, it can be accessed using JDBC/ODBC and with variety of PostgreSQL clients along with OData.  See instructions xref:jdbc.adoc[here]

