= Installing the Operator [[dv-install]]
Before you install the Operator for Teiid, make sure you have access to an OpenShift Instance. You may also install a local xref:minishift.adoc[minishift].


== On OpenShift 3.11 [[ocp311]]
If you are working with OpenShift 3.11 then follow the instructions below. Make sure you have access to an OpenShift instance and you have `Cluster Admin` privileges to install the Operator. If you are working with local a `minishift` instance then all the permissions needed are available through the `admin` user.

[source,bash]
----
oc login 

export OP_ROOT=https://raw.githubusercontent.com/teiid/teiid-operator/master/deploy
oc create -f $OP_ROOT/crds/virtualdatabase.crd.yaml
oc create -f $OP_ROOT/service_account.yaml
oc create -f $OP_ROOT/role.yaml
oc create -f $OP_ROOT/role_binding.yaml
oc create -f $OP_ROOT/operator.yaml
----

or, there is a script available with the above, execute

[source,bash]
----
oc login

./install-operator.sh
----


If there were no errors, you should have a Teiid Operator deployed in your OpenShift instance in the logged in namespace. You can now use the `VirtualDatabase Deployment` section to create and deploy a VDB as an image.


== On OpenShift 4.2 or later [[ocp4]]
On the OpenShift 4.2 later the Teiid Operator is available through OperatorHub. Go to the Operator catalog and find and install the `Teiid Operator`

