== Instructions to Install Minishift

Before you begin, you must have access to OpenShift Dedicated cluster, or `minishift` or `oc cluster up` running and have access the the instance.

* Requires minishift 1.25+ and openshift client 3.9+.   Minishift 1.31 defaults to its own 3.10 version of oc client.

* To install [minishift](https://www.okd.io/minishift/); which is available for all the major operating systems (Linux, OS X and Windows). This example assumes that you have Minishift installed and can be called from the command line. So, minishift must be available in your search path, i.e. located in a directory contained in your $PATH environment variable (Linux, macOS) or in a directory from your system path (Windows)

* If you are using minishift for fist time you can start using the below command

[source,bash]
----
$minishift start --cpus 2 --memory 8GB --disk-size 40GB
----

* Once the Minishift based OpenShift is started, log into OpenShift using the command line. You can use the default username/password of developer/developer, if no credentials have been configured.

[source,bash]
----
$oc login
----

The ip of the minishift instance will be shown by the login, or may be obtained by running `$minishif ip`

* Create a new namespace in the OpenShift, i.e. a new project in OpenShift, this is the namespace we will be deploying the vdb-service into.

[source,bash]
----
$oc new-project myproject
----

* Log into the OpenShift Web Console application using the https://ip:8443/console.