= Securing PG/JDBC with Keycloak 

This example is continuation of xref:keycloak-odata-sso.adoc[OData with Keycloak].  The tasks in there should be completed first before going through this example.

The main aim in this example is to secure the Data Virtualization's PG/JDBC socket transports with Keycloak. We will use OpenID-Connect as authentication mechanism via Direct Access Grants and use OAuth2 as the authorization mechanism. 


NOTE: Configuration wise it is exactly same as the xref:keycloak-odata-sso.adoc[OData with Keycloak]. 

If the user is using jdbc/pg service ports to access the Virtual Database, now they will be subject to authentication based on userid and password.

If the user has need to expose these ports beyond OpenShift then follow through the Post Deployment section.

== Post Deployment

Now you should see that the image you deployed into the OpenShift is active and running.  To expose the Teiid PG secure port for external access, use:

[source,yaml]
----
$oc create -f - <<INGRESS
apiVersion: v1
kind: Service
metadata:
  name: security-example-ingress
spec:
  ports:
  - name: teiid-pg-secure
    port: 35443
  type: LoadBalancer 
  selector:
    app: security-example
  sessionAffinity: ClientIP
INGRESS
----

To determine the ip/port run: 

[source,bash]
----
$oc get svc security-example-ingress
----

Note that the secure transport will use a private key based upon the OpenShift managed service signing certificate.  

You may similarly choose to expose the Teiid JDBC port, or modify the example to expose the secure Teiid JDBC port.

==  Testing

If you use `user` as the user name when you login, you will be granted to view the data of the customer view. If you used `developer` as the user name, the permission to view the customer data is not granted, as the `developer` user does not have the `ReadRole` role.

There is a `simple-jdbc-client` example in the directory above.  You may test against the PG host/port exposed by the LoadBalancer by altering its `application-pg-secure.properties` to match the host and port.  You may of course test against a locally launched instance as well.
