== Virtualization as Maven Artifact

This example has two sub-projects, `vdb-builder` which shows how a vdb file can be defined inside a maven project to build a artifact with `.vdb` extension but more importantly version it using the maven and put it into a maven repository. 

In this model, VDB can be defined in exploded format, as in, a single DDL file does not need to contain all the schema for every model, a separate DDL files can be defined. You can also include additional library files in "lib" directory. However, there *MUST* be one main vdb file called `vdb.ddl` in the `src/main/vdb` folder. This vdb folder can contain any number of sub-folders as needed to separate the code as needed. When the maven build is runs, it will scan through `src/main/vdb` folder and builds an artifact with name `${project.name}-${version}.vdb` file, and also places this artifact in the maven repository.

When build runs, it will also resolve any `vdb-import` statements in the main VDB, and pull in the contents for the imported vdbs from additional vdb files that are defined in the `src/main/vdb` folder like for example `/src/main/vdb/import/foo-vdb.ddl` where the `foo` vdb is imported in your main VDB. Alternatively, you can define a maven dependency like

[source,xml]
----
<dependency>
    <groupId>com.example</groupId>
    <artifactId>customer-vdb</artifactId>
    <version>${project.version}</version>
    <type>vdb</type>
</dependency>
----

in the `pom.xml` file as dependency, and the plugin will find the file and resolve the contents appropriately.

NOTE: `vdb-import` are only allowed at top level vdb, no nesting allowed. If nesting is needed, build the intermediate VDBs as top level vdb maven artifacts, and then use them as imports into others, essentially keeping the nesting to single level.

All above is to build a VDB that can be used else where with Operator for deployment, or to be imported into other VDBs.

==== Local Build & Run

For local build run requires the second project in `vdb-run`, which imports the above vdb as a maven dependency and generates the necessary code.

Once you define the above files, one can build the virtualization using the command

[source,bash]
----
mvn clean install
----

make sure the build is completed without any errors. Now, if the database is accessible from the machine where this build is ran, and configuration in the `application.properties` file points to the correct database, then you can run the virtualization locally for any testing by executing

[source,bash]
----
java -jar vdb-run/target/vdb-run-1.0.0.jar
----

Once the above program is started fully without any errors, then you can connect your JDBC/ODBC or any other clients to access the data.

NOTE: The above is only for local testing.


== Deployment to OpenShift

When VDB is available in Maven, there can be two options available for deploying. Option 2 is recommended way.

==== Option 1
When project is defined in this fashion, it is expected that above project is available in a git repository location, which then be used by the Operator to reference and deploy.

The configuration for the data source(s) is defined in a `custom resource` file. For this example see, `custom resource` defined in  link:dv-customer-git.yaml[dv-customer-git.yaml]

NOTE: A bug has been found which prohibits deploying this currently, which is reported at TEIIDSB-131 will be fixed in next iteration.

==== Option 2
Instead of using git location for the VDB, you also supply VDB's maven location for deploying.

The configuration for the data source(s) is defined in a `custom resource` file. For this example see, `custom resource` defined in  link:dv-customer-maven.yaml[dv-customer-maven.yaml]

NOTE: Support for this model deployment is currently not available in the Operator, will be available in next release. See TEIIDTOOLS-781


Once the full fill the prerequisites, one can issue following command to deploy the virtualization into OpenShift.

[source,bash]
----
oc create -f dv-customer-git.yaml
----

once completed it will have a Service called `dv-customer` with ports open for jdbc and pg protocols.

If you want to delete the above virtualization, execute

[source,bash]
----
oc delete vdb dv-customer
----

Once the above program is started fully without any errors, then you can connect your JDBC/ODBC or any other clients to access the data. See link:../Readme.adoc#vdb-access[Accessing the deployed Virtualization]